package by.talstaya.crackertracker.command;

/**
 * This enum contains all possible command than can come from a request
 *
 * @author Anna Talstaya
 * @version 1.0
 */
public enum CommandType {
    VISIT_SIGN_IN,
    SIGN_IN,
    SIGN_OUT,
    VISIT_REGISTRATION,
    REGISTRATION,
    TRANSLATE,
    VISIT_SETTINGS,
    SETTINGS,
    ADD_MEAL,
    VISIT_PRODUCT_LIST,
    PRODUCT_LIST,
    SEARCH,
    SHOW_PRODUCT_DETAILS,
    DIET,
    SHOW_DIET,
    DELETE_MEAL,
    UPDATE_QUANTITY_IN_DIET,
    USER_LIST,
    SHOW_USER_DETAILS,
    CHANGE_USER_TYPE,
    DELETE_USER,
    SHOW_SUPERVISOR,
    SUPERVISOR_LIST,
    SEND_REQUEST_FOR_SUPERVISOR,
    DELETE_REQUEST_FOR_SUPERVISOR,
    USER_LIST_OF_SUPERVISOR,
    SHOW_REQUESTS_FOR_SUPERVISOR,
    SUPERVISOR_ACCEPTS_REQUEST,
    SUPERVISOR_REJECTS_REQUEST,
    DELETE_USER_OF_SUPERVISOR,
    DELETE_SUPERVISOR,
    RATE_SUPERVISOR,
    COMMENT,
    DELETE_COMMENT,
    USER_DIET_FOR_SUPERVISOR,
    SHOW_USER_DIET_FOR_SUPERVISOR,

}
